DAY4/TrainningPortalWebApplication/TrainningPortalWebApplication/Models/ErrorViewModel.cs
namespace TrainningPortalWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DAY4/TrainningPortalWebApplication/TrainningPortalWebApplication/Controllers/TrainingController.cs
using Microsoft.AspNetCore.Mvc;

namespace TrainningPortal.Controllers
{
    public class TrainingController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Courses()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
    }
}

DAY4/TrainningPortalWebApplication/TrainningPortalWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainningPortalWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrainningPortalWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrainningPortalWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Training"
                               asp-action="Index">Training</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Training"
                               asp-action="Courses">Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Training"
                               asp-action="Contact">Contact</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>




    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - TrainningPortalWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DAY4/TrainningPortalWebApplication/TrainningPortalWebApplication/Views/Training/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Contact Us</h1>
<p>Email: training@college.com</p>
<p>Phone: +91 9876543210</p>

DAY4/TrainningPortalWebApplication/TrainningPortalWebApplication/Views/Training/Courses.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Courses</h1>
<ul>
    <li>ASP.NET Core MVC</li>
    <li>Web Development</li>
    <li>Database Fundamentals</li>
</ul>

DAY4/TrainningPortalWebApplication/TrainningPortalWebApplication/Views/Training/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Welcome to Training Portal</h1>
<p>This portal provides information about our training programs.</p>